POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "juules",
    "name": "julia",
    "password": "whatever"
}
###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "jules",
    "password": "whatever"
}
###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhY2EiLCJpZCI6IjY3ODdmNWZlZThhNTU4NDIwM2U4N2Q3ZiIsImlhdCI6MTczNzEzNjM2NX0.sreYdH1HzpwjtmRUBzqJj8t1rlzxFhWqOfHgwbxdg_0

{
    "title": "Tercer Blog",
    "url": "blog.com",
    "author": "JULIA CASARES",
    "likes": 5
}
###

DELETE http://localhost:3001/api/blogs/679233069aa04320b99d0f1b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhY2EiLCJpZCI6IjY3ODdmNWZlZThhNTU4NDIwM2U4N2Q3ZiIsImlhdCI6MTczNzEzNjM2NX0.sreYdH1HzpwjtmRUBzqJj8t1rlzxFhWqOfHgwbxdg_0
###

GET http://localhost:3001/api/blogs/67ae3470ec1dca95301c298f
###

PUT http://localhost:3001/api/blogs/67ae3470ec1dca95301c298f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1bGVzIiwiaWQiOiI2Nzk3Y2U3NWZiNTQ4ZmE5YTMxNTI3M2IiLCJpYXQiOjE3Mzk0Njg0NjF9.kjHbVOu_MwftXZyYqvnr3GsOzQpwaIzzxEGdPTwBGDI

{
  "user": "6797ce75fb548fa9a315273b",
  "likes": 1,
  "author": "Julesss",
  "title": "Blog ejercicio 5.8",
  "url": "ldjnelkfmk"
}
